obj-$(CONFIG_CV1835_SYSDMA_REMAP)	+= sysdma/cv1835_dma_remap.o
obj-$(CONFIG_CVI_WIFI_PIN)	+= wifi_pin/cvi_wifi_pin.o
obj-$(CONFIG_CVI_BT_PIN)	+= bt_pin/cvi_bt_pin.o
obj-$(CONFIG_CVI_MAIL_BOX)	+= rtos_cmdqu/rtos_cmdqu.o rtos_cmdqu/cvi_spinlock.o rtos_cmdqu/rtos_cmdqu_cb.o